### ISSUE TITLE
Question: latex grammar for tree-sitter ?

### ISSUE THREAD

**Issue by gracile-fr** [Aerijo/latex-folding#1]
Hello,
I'm coming from: https://github.com/area/language-latex/issues/132.
Are you going to use tree-sitter for latex code folding as described <a href="https://github.com/atom/atom/pull/16299">here</a>? That would be great but if I understand correctly, there's no latex grammar for tree-sitter at the moment ?

**Comment by Aerijo** [comment]
Sorry, I made this repo without realising I had no time to actually start it. I've released the first version now though, and it seems to work well in my testing. More detailed README will follow.

As for tree-sitter, that's not required for this package. Instead, it uses markers to keep track of section commands, rebuilding them everytime you stop typing.

I am looking to get back on building a tree-sitter grammar for LaTeX. I'm not sure if it will help for code folding, as I don't think I'll make the `section`, etc., commands part of the syntax tree. I'll have to wait and see how to make it all work though.

**Comment by gracile-fr** [comment]
I'm looking for something very simple : the ability to fold section, subsection, paragraph, subparagraph, etc. ands also footnotes (`\footcite` etc.).
I read you added some code folding in https://github.com/Aerijo/latex-wordcount ? What's the difference with this one?

> I am looking to get back on building a tree-sitter grammar for LaTeX. 
What about this: https://github.com/yitzchak/tree-sitter-latex ?

**Comment by Aerijo** [comment]
Right now this package can fold section, subsection, subsusbsection, and environments. I can add support for paragraph, etc, easily. 

I don't know much about how folding footnotes would work, but if you give an example I could try to support it. Currently, I've restricted support to commands that begin the line, so it doesn't waste time looking through entire paragraphs of text. I could experiment though, to see if lifting this doesn't affect performance.

> I read you added some code folding in https://github.com/Aerijo/latex-wordcount ? What's the difference with this one?

It's pretty much the same. The difference is how it's done. With this one, the folding is like native folding, so you use the arrows next to the line numbers. With the original one, you had to run a command to fold a section. I plan on adding the command version to this one too, and removing folding completely from the word count package.

> What about this: https://github.com/yitzchak/tree-sitter-latex ?

As for that tree sitter grammar, I would like to try writing my own.

**Comment by gracile-fr** [comment]
Thanks. Unfortunately I am not able to install your package from Atom Settings->Install…

**Comment by Aerijo** [comment]
Is it an error, or just not visible?

**Comment by Aerijo** [comment]
If not visible, you may need to type in the exact name `latex-folding` and scroll down a lot.

Alternatively, try running `apm install latex-folding` in the command line / terminal / command prompt.

**Comment by gracile-fr** [comment]
It is visible, when I click on "Install", the button has the grey&white stripes showing an activity, but then nothing happens (Atom 1.27.2 and Win7 64bits).

**Comment by Aerijo** [comment]
Hmm. I get that occaisionally when installing packages. Does the command work? I find that can be more reliable.

**Comment by gracile-fr** [comment]
No the command doesn't work:

```
C:\Users\gracile-fr>apm install latex-folding
Installing latex-folding to C:\Users\gracile-fr\.atom\packages failed

> oniguruma@6.2.1 install C:\Users\GRACILE-FR\AppData\Local\Temp\apm-install-dir-1
18515-2632-1txazgz.67wihhbyb9\node_modules\latex-folding\node_modules\oniguruma
> node-gyp rebuild


C:\Users\GRACILE-FR\AppData\Local\Temp\apm-install-dir-118515-2632-1txazgz.67wihhb
yb9\node_modules\latex-folding\node_modules\oniguruma>if not defined npm_config_
node_gyp (node "C:\Users\gracile-fr\AppData\Local\atom\app-1.27.2\resources\app\ap
m\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild )  else (node "C:\Users\gracile-fr\AppData\Local\atom\app-1.27.2\resourc
es\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
C:\Users\GRACILE-FR\AppData\Local\Temp\apm-install-dir-118515-2632-1txazgz.67wihhb
yb9
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coff
eescript" (no hyphen)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\gracile-fr\AppData\Local\atom\app-1.2
7.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\gracile-fr\AppData\Local\atom\app-1.27.2\resources\
app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\gracile-fr\AppData\Local\atom\app-1.27.2\resources\
app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\gracile-fr\\AppData\\Local\\atom\\app-1.27.2\\resourc
es\\app\\apm\\bin\\node.exe" "C:\\Users\\gracile-fr\\AppData\\Local\\atom\\app-1.2
7.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\GRACILE-FR\AppData\Local\Temp\apm-install-dir-118515-2632-1t
xazgz.67wihhbyb9\node_modules\latex-folding\node_modules\oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\GRACILE-FR\AppDa
ta\Local\Temp\apm-install-dir-118515-2632-1txazgz.67wihhbyb9\package.json'
npm WARN apm-install-dir-118515-2632-1txazgz.67wihhbyb9 No description
npm WARN apm-install-dir-118515-2632-1txazgz.67wihhbyb9 No repository field.
npm WARN apm-install-dir-118515-2632-1txazgz.67wihhbyb9 No README data
npm WARN apm-install-dir-118515-2632-1txazgz.67wihhbyb9 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\gracile-fr\\AppData\\Local\\atom\\app-1.27.2\\resources\
\app\\apm\\bin\\node.exe" "C:\\Users\\gracile-fr\\AppData\\Local\\atom\\app-1.27.2
\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\
\Users\\gracile-fr\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\gracile-fr\\.ato
m\\.apmrc" "install" "C:\\Users\\GRACILE-FR\\AppData\\Local\\Temp\\d-118515-2632-z
r0zs8.9etxogvi\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64"
 "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GRACILE-FR\AppData\Local\Temp\apm-install-dir-118515-2632-1t
xazgz.67wihhbyb9\npm-debug.log
npm ERR! code 1
```

**Comment by Aerijo** [comment]
Oh. `node-gyp`. I've run into that before.

Fortunately, it only had a minor role. I've removed it as a dependency, so the patched version should work.
