### ISSUE TITLE
Suggestion: Allow for spacing when folding

### ISSUE THREAD

**Issue by Elthan** [Aerijo/latex-folding#4]
First of all, thank you for creating this, it's a wonderful tool that helps a lot when writing larger and messier documents!

The only issue I have found so far is that when folding text it will include spaces after the text and before the next section in the fold, i.e. the fold includes spaces that it should not.

Example:
```latex
\section{Lorem}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tristique lacus nec dui semper finibus id et ipsum.
Morbi ut odio vitae ex accumsan dignissim vitae sed orci. Mauris vitae consequat nibh. Sed sagittis orci ut nulla vulputate varius. 
Cras a tempor lectus. Integer massa orci, finibus eu consectetur dictum, convallis sit amet magna.

\section{Ipsum}
Sed porttitor sapien eu lorem mattis, et gravida nulla mollis. 
Etiam purus tortor, efficitur lacinia orci sit amet, feugiat egestas mi.
Proin quis consequat purus. Mauris lobortis diam diam, vitae lobortis est facilisis nec.
Aenean elementum eros sit amet ligula bibendum faucibus. 
```

When folded this becomes:

```latex
\section{Lorem}
\section{Ipsum}
Sed porttitor sapien eu lorem mattis, et gravida nulla mollis. Etiam purus tortor, efficitur lacinia orci sit amet, feugiat egestas mi. Proin quis consequat purus. Mauris lobortis diam diam, vitae lobortis est facilisis nec. Aenean elementum eros sit amet ligula bibendum faucibus. 
```
As you can see the space above the Ipsum section disappears in the fold. This makes it harder to separate each section when folding, at least for me.

**Comment by Aerijo** [comment]
Hmmm, should be a straightforward fix.

**Comment by Aerijo** [comment]
Should work in the new release. Default is to leave whitespace, but there is an option to fold it like before.

**Comment by Elthan** [comment]
That works perfectly. Thank you for the quick response!
